title: Bo Han's Blog
author: Bo Han

# markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

# permalink: /posts/:title/
permalink: /posts/:title

# local test set favicon
favicon_ico: /favicon.ico

# pagination
paginate: 10 # 每页显示的条数
paginate_path: "/blog/page:num/" # 分页生成的路径

# generate social links
social_links:
  github: HBhakunamatata
  linkedIn: hanbo
  mail: hanbo9501@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
